Repository kubewarden/container-resources-policy, pull requests merged in 2024-01, with the labels that each got.

#1 feat: init policy code.
  .github/workflows/release.yml
  .github/workflows/reusable-test-policy-go.yml
  .github/workflows/test.yml
  .gitignore
  CODEOWNERS
  Dockerfile
  LICENSE
  Makefile
  README.md
  artifacthub-pkg.yml
  artifacthub-repo.yml
  e2e.bats
  go.mod
  go.sum
  main.go
  metadata.yml
  renovate.json
  resource/README.md
  resource/amount.go
  resource/math.go
  resource/quantity.go
  resource/quantity_test.go
  resource/scale_int.go
  resource/suffix.go
  settings.go
  settings_test.go
  test_data/deployment_with_limits_admission_request.json
  test_data/deployment_with_requests_resources_admission_request.json
  test_data/deployment_without_resources_admission_request.json
  test_data/pod_exceeding_range.json
  test_data/pod_within_range.json
  validate.go
  validate_test.go
  wasi-gh-action.json
  wasi.json
Labels: kind/enhancement

#5 feat: e2e test to checking settings validation.
  e2e.bats
Labels: kind/enhancement

#7 fix: missing questions-ui.yml
  Makefile
  artifacthub-pkg.yml
  questions-ui.yml
Labels: kind/bug, area/ui

#9 chore(deps): update to latest version of k8s-objects
  go.mod
  go.sum
Labels: kind/bug, dependencies
